
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: reporadar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/reporadar
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings_prod
      - DJANGO_SECRET_KEY=change-this-in-production-very-secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ALLOWED_HOSTS=*
      - APP_BASE_URL=https://main.d25lyjl7b5u7se.amplifyapp.com
    depends_on:
      - db
      - redis
    restart: always

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from https://13-49-0-249.sslip.io --to web:8000
    depends_on:
      - web

  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/reporadar
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings_prod
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db
      - redis
    restart: always

  celery_beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/reporadar
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings_prod
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
