# Generated by Django 6.0.5 on 2026-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_repoagentsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepoAgentSession',
        ),
    ]
